# Generated by Django 5.2 on 2025-04-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_event_google_calendar_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='student_email',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.TextField(default=''),
        ),
    ]
