# Generated by Django 5.2 on 2025-04-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_googletoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meet_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
